print("Hello, World")
print("Demo")
print("hello")
print("Sandeep")
print("Raghav")
print("piyush")
print("Mohammad Raza")
print("Devraj")
print(" raghav......")
print("Md Motiullah")
print("Jay")
print("ROHIT")
print("Rohit_SIKARI")
print("HELLO_EVERYONE")
print("Aakansha")
print("DATA SCIENCE")
print("Vipul changed the design after lecture")
<<<<<<< HEAD
print("paridhi")
=======
print("Palak")
>>>>>>> 66210b1e13bde3e93cf5d71c5ae16e4f35d45d1c
